name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get Release Subject
        id: subject
        run: 'echo ::set-output name=SUBJECT::$(git tag -l --format="%(contents:subject)" $GITHUB_REF_NAME)'
      - name: Make Release Notes File
        run: 'echo "$(git tag -l --format="%(contents:body)" $GITHUB_REF_NAME)" > RELEASE_NOTES'
      - name: Publish GitHub Release
        run: 'gh release create "$GITHUB_REF_NAME" -F RELEASE_NOTES -t "${{ steps.subject.outputs.SUBJECT }}"'
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
